import { AgentInfo, Finding, Investigation } from "./types";
import { TrustGraphNode, TrustGraphEdge, TrustGraphData } from "./api/client";

export const MOCK_AGENTS: AgentInfo[] = [
  {
    id: "pii-scanner",
    name: "PII Scanner",
    role: "Detection and sanitization of sensitive personal data",
    model: "Gemma 2B (Vertex AI)",
    status: "COMPLETED",
    currentTask: "Scanning for SSNs, tax IDs, emails and personal identifiers",
    confidence: 0.98,
    findingsCount: 3,
    lastExecutionMs: 420,
  },
  {
    id: "lgpd-specialist",
    name: "LGPD Specialist",
    role: "Compliance assessment against Brazilian Law 13,709/2018",
    model: "Gemini 1.5 Flash",
    status: "COMPLETED",
    currentTask: "Analysis of lawful bases and processing termination (Art. 15 & 16)",
    confidence: 0.94,
    findingsCount: 4,
    lastExecutionMs: 1250,
  },
  {
    id: "gdpr-specialist",
    name: "GDPR Specialist",
    role: "Compliance with Art. 5(1)(e) & Art. 17 (Right to Erasure)",
    model: "Gemini 1.5 Flash",
    status: "COMPLETED",
    currentTask: "Verification of cross-border data retention timeframes",
    confidence: 0.91,
    findingsCount: 2,
    lastExecutionMs: 1100,
  },
  {
    id: "iso-specialist",
    name: "ISO 27001 Specialist",
    role: "Media retention and secure disposal controls (A.8.10)",
    model: "Gemini 1.5 Flash",
    status: "COMPLETED",
    currentTask: "Mapping secure purging protocols and encryption at rest",
    confidence: 0.96,
    findingsCount: 1,
    lastExecutionMs: 980,
  },
  {
    id: "evidence-critic",
    name: "Evidence Critic",
    role: "Adversarial review and hypothesis cross-examination",
    model: "Gemini 2.5 Pro",
    status: "COMPLETED",
    currentTask: "Challenging findings to eliminate false positive claims",
    confidence: 0.97,
    findingsCount: 0,
    lastExecutionMs: 2300,
  },
];

export const MOCK_INVESTIGATIONS: Investigation[] = [
  {
    id: "INV-2024-0047",
    title: "Corporate Data Retention Policy (Multi-Jurisdiction)",
    documentName: "corporate_data_retention_policy_v2.pdf",
    documentHash: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    fileSizeBytes: 245800,
    createdAt: "2026-08-30T13:30:00Z",
    updatedAt: "2026-08-30T15:20:00Z",
    status: "COMPLETED",
    progressPercent: 100,
    frameworks: ["LGPD", "GDPR", "ISO 27001"],
    findingsCount: {
      total: 6,
      critical: 2,
      high: 2,
      medium: 1,
      low: 1,
    },
  },
  {
    id: "INV-2024-0046",
    title: "Mobile App Terms of Service & Privacy Policy",
    documentName: "mobile_terms_and_privacy_v1.md",
    documentHash: "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08",
    fileSizeBytes: 112400,
    createdAt: "2026-08-29T10:15:00Z",
    updatedAt: "2026-08-29T11:45:00Z",
    status: "COMPLETED",
    progressPercent: 100,
    frameworks: ["LGPD", "OWASP"],
    findingsCount: {
      total: 4,
      critical: 1,
      high: 1,
      medium: 1,
      low: 1,
    },
  },
];

export const MOCK_FINDINGS: Finding[] = [
  {
    id: "FIND-01",
    investigationId: "INV-2024-0047",
    title: "Indefinite Retention of User Personal Data",
    description: "Section 2.1 specifies indefinite storage without lawful basis for processing termination, violating the necessity and storage limitation principles.",
    severity: "CRITICAL",
    framework: "LGPD",
    articleOrControl: "Art. 15 & Art. 16 (Processing Termination & Erasure)",
    agentId: "lgpd-specialist",
    agentName: "LGPD Specialist (Gemini Flash)",
    confidence: 0.95,
    evidenceQuote: "User profile data and transaction history shall be stored indefinitely for business intelligence and service personalization purposes...",
    evidenceHash: "8f4b2a1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b7c6d5e4f3a",
    remediationSuggestion: "Define a maximum 5-year retention period after account closure and implement automated purging schedules.",
    status: "OPEN",
    challengedByCritic: true,
    criticVerdict: "Validated: No legitimate legal basis for perpetual retention exists under LGPD without effective anonymization.",
  },
  {
    id: "FIND-02",
    investigationId: "INV-2024-0047",
    title: "Excessive Response Window for Right to Erasure (90 Days)",
    description: "Section 3.1 sets a 90-business-day window for deletion request review, exceeding the statutory 30-day requirement under GDPR.",
    severity: "CRITICAL",
    framework: "GDPR",
    articleOrControl: "Art. 17 (Right to Erasure) & Art. 12(3)",
    agentId: "gdpr-specialist",
    agentName: "GDPR Specialist (Gemini Flash)",
    confidence: 0.92,
    evidenceQuote: "Requests for personal data deletion submitted by data subjects will be reviewed by the legal team within 90 business days.",
    evidenceHash: "7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b7c6d5e4f3a2b1c0d9e8f7a6b",
    remediationSuggestion: "Reduce the statutory response timeframe to 30 calendar days pursuant to GDPR Article 12(3).",
    status: "OPEN",
    challengedByCritic: true,
    criticVerdict: "Confirmed: GDPR mandates a 1-month timeframe, extendable only with substantiated notice of complexity to the data subject.",
  },
  {
    id: "FIND-03",
    investigationId: "INV-2024-0047",
    title: "Server Logs with IP Addresses Retained Without Anonymization",
    description: "Section 2.2 retains server access logs for 30 days containing personal identifiers without pseudonymization or IP masking.",
    severity: "HIGH",
    framework: "ISO 27001",
    articleOrControl: "Control A.8.10 (Information Deletion) & A.8.15 (Logging)",
    agentId: "iso-specialist",
    agentName: "ISO 27001 Specialist (Gemini Flash)",
    confidence: 0.88,
    evidenceQuote: "Server access logs and HTTP requests will be retained for thirty (30) days without automated purging of records containing IP addresses...",
    evidenceHash: "1e0f9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f",
    remediationSuggestion: "Implement subnet masking on the last IP octet during real-time log ingestion pipelines.",
    status: "OPEN",
    challengedByCritic: false,
  },
  {
    id: "FIND-04",
    investigationId: "INV-2024-0047",
    title: "Shared Generic Credentials in Analytical Databases",
    description: "Section 4.1 mentions shared generic credentials across the engineering team, violating least privilege and individual session traceability.",
    severity: "HIGH",
    framework: "ISO 27001",
    articleOrControl: "Control A.5.15 (Access Control) & A.9.2 (User Access Management)",
    agentId: "iso-specialist",
    agentName: "ISO 27001 Specialist (Gemini Flash)",
    confidence: 0.96,
    evidenceQuote: "Analytical databases utilize shared passwords restricted to the engineering team.",
    evidenceHash: "5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d",
    remediationSuggestion: "Migrate to federated SSO/IAM authentication with individual named accounts and audit trails.",
    status: "OPEN",
    challengedByCritic: true,
    criticVerdict: "Critical: Shared credentials eliminate individual session traceability required by ISO 27001.",
  },
];

export const MOCK_TRUST_GRAPH_INITIAL: TrustGraphData = {
  investigation_id: "INV-2024-0047",
  total_nodes: 10,
  valid_nodes: 10,
  invalid_nodes: 0,
  nodes: [
    {
      id: "req-lgpd-16",
      type: "requirement",
      source: "LGPD Art. 16 (Data Deletion)",
      valid: true,
      confidence: 1.0,
      jurisdiction: "BR",
      content_hash: "sha256-lgpd-art16-v1",
      details: "Mandates deletion upon completion of personal data processing purpose.",
    },
    {
      id: "req-gdpr-5",
      type: "requirement",
      source: "GDPR Art. 5(1)(e) (Storage Limitation v1)",
      valid: true,
      confidence: 1.0,
      jurisdiction: "EU",
      content_hash: "sha256-gdpr-art5-v1",
      details: "Personal data shall not be kept longer than necessary for the purpose.",
    },
    {
      id: "req-iso-a810",
      type: "requirement",
      source: "ISO 27001 A.8.10 (Data Deletion)",
      valid: true,
      confidence: 1.0,
      jurisdiction: "GLOBAL",
      content_hash: "sha256-iso-a810-v1",
      details: "Guidelines for secure disposal and audit trail retention schedules.",
    },
    {
      id: "ag-pii",
      type: "agent",
      source: "PII Scanner (Gemma 2B)",
      valid: true,
      confidence: 0.98,
      jurisdiction: "ALL",
      content_hash: "sha256-agent-pii-v1",
      details: "Preliminary scan for SSNs, emails and confidential identifiers.",
    },
    {
      id: "ag-lgpd",
      type: "agent",
      source: "LGPD Specialist (Gemini 1.5 Flash)",
      valid: true,
      confidence: 0.94,
      jurisdiction: "BR",
      content_hash: "sha256-agent-lgpd-v1",
      details: "Brazilian national data privacy compliance agent.",
    },
    {
      id: "ag-gdpr",
      type: "agent",
      source: "GDPR Specialist (Gemini 1.5 Flash)",
      valid: true,
      confidence: 0.91,
      jurisdiction: "EU",
      content_hash: "sha256-agent-gdpr-v1",
      details: "European Union regulatory privacy specialist agent.",
    },
    {
      id: "ev-retencao-infinita",
      type: "evidence",
      source: "corporate_policy.pdf §2.1",
      valid: true,
      confidence: 0.95,
      jurisdiction: "BR/EU",
      content_hash: "8f4b2a1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b7c6d5e4f3a",
      details: "Exact quote: '...shall be stored indefinitely for business intelligence...'",
    },
    {
      id: "ev-prazo-90dias",
      type: "evidence",
      source: "corporate_policy.pdf §3.1",
      valid: true,
      confidence: 0.92,
      jurisdiction: "EU",
      content_hash: "7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b7c6d5e4f3a2b1c0d9e8f7a6b",
      details: "Exact quote: '...reviewed by legal team within 90 business days.'",
    },
    {
      id: "find-01-node",
      type: "finding",
      source: "FIND-01: Indefinite Retention",
      valid: true,
      confidence: 0.95,
      jurisdiction: "BR",
      content_hash: "sha256-find-01",
      details: "Non-compliance with LGPD Art. 16. Remediation patch required.",
    },
    {
      id: "find-02-node",
      type: "finding",
      source: "FIND-02: Excessive 90d Window",
      valid: true,
      confidence: 0.92,
      jurisdiction: "EU",
      content_hash: "sha256-find-02",
      details: "Violation of GDPR Art. 12 statutory 30-day response window.",
    },
  ],
  edges: [
    { from: "req-lgpd-16", to: "find-01-node" },
    { from: "ag-lgpd", to: "find-01-node" },
    { from: "ev-retencao-infinita", to: "find-01-node" },
    { from: "ag-pii", to: "ev-retencao-infinita" },
    { from: "req-gdpr-5", to: "find-02-node" },
    { from: "ag-gdpr", to: "find-02-node" },
    { from: "ev-prazo-90dias", to: "find-02-node" },
    { from: "req-iso-a810", to: "ev-retencao-infinita" },
  ],
};

export const SAMPLE_POLICIES = [
  {
    name: "Corporate Data Retention Policy — Synthetic BR/EU",
    description: "Official multi-jurisdiction demo scenario (LGPD + GDPR + ISO 27001)",
    frameworks: ["LGPD", "GDPR", "ISO 27001"],
    sampleContent: `CORPORATE DATA RETENTION & PRIVACY POLICY
Version 2.4 — September 2026

1. PURPOSE & SCOPE
This policy establishes governing rules for storage, processing, and disposal of personal and corporate data handled across AEGIS Group production environments in Brazil and the European Union.

2. RETENTION PERIODS
2.1. User profile data and transaction history shall be stored indefinitely for business intelligence and service personalization purposes.
2.2. Server access logs and HTTP requests will be retained for thirty (30) days without automated purging of records containing IP addresses or personal identifiers.
2.3. Tax records and financial transaction receipts will be preserved for five (5) years in compliance with applicable fiscal legislation.

3. RIGHT TO ERASURE & DATA DELETION
3.1. Requests for personal data deletion submitted by data subjects will be reviewed by the legal team within 90 business days.
3.2. Data held in cold backups is exempt from real-time deletion requests and will be overwritten exclusively during standard 2-year tape rotation cycles.

4. SECURITY & ENCRYPTION
4.1. Data in transit is secured with TLS 1.3. Analytical databases utilize shared passwords restricted to the engineering team.`,
  },
];
