import { AgentInfo, Finding, Investigation } from "./types";
import { TrustGraphNode, TrustGraphEdge, TrustGraphData } from "./api/client";

export const MOCK_AGENTS: AgentInfo[] = [
  {
    id: "pii-scanner",
    name: "PII Scanner",
    role: "Detecção e sanitização de dados pessoais sensíveis",
    model: "Gemma (Vertex AI)",
    status: "COMPLETED",
    currentTask: "Varredura de CPF, RG, emails e identificadores únicos",
    confidence: 0.98,
    findingsCount: 3,
    lastExecutionMs: 420,
  },
  {
    id: "lgpd-specialist",
    name: "Especialista LGPD",
    role: "Avaliação de conformidade com a Lei 13.709/2018",
    model: "Gemini 2.5 Flash",
    status: "COMPLETED",
    currentTask: "Análise de bases legais e término de tratamento (Art. 15 e 16)",
    confidence: 0.94,
    findingsCount: 4,
    lastExecutionMs: 1250,
  },
  {
    id: "gdpr-specialist",
    name: "Especialista GDPR",
    role: "Conformidade com Art. 5(1)(e) e Art. 17 (Direito ao Esquecimento)",
    model: "Gemini 2.5 Flash",
    status: "COMPLETED",
    currentTask: "Verificação de prazos de retenção transfronteiriços",
    confidence: 0.91,
    findingsCount: 2,
    lastExecutionMs: 1100,
  },
  {
    id: "iso-specialist",
    name: "Especialista ISO 27001",
    role: "Controles de retenção e destruição de mídia (A.8.10)",
    model: "Gemini 2.5 Flash",
    status: "COMPLETED",
    currentTask: "Mapeamento de descarte seguro e criptografia em repouso",
    confidence: 0.96,
    findingsCount: 1,
    lastExecutionMs: 980,
  },
  {
    id: "evidence-critic",
    name: "Evidence Critic",
    role: "Revisão adversarial e questionamento de conclusões",
    model: "Gemini 2.5 Pro",
    status: "COMPLETED",
    currentTask: "Desafiando evidências para eliminar falsos positivos",
    confidence: 0.97,
    findingsCount: 0,
    lastExecutionMs: 2300,
  },
];

export const MOCK_INVESTIGATIONS: Investigation[] = [
  {
    id: "INV-2024-0047",
    title: "Política de Retenção de Dados Corporativos (Multi-Jurisdição)",
    documentName: "politica_retencao_dados_v2.pdf",
    documentHash: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    fileSizeBytes: 245800,
    createdAt: "2026-08-30T13:30:00Z",
    updatedAt: "2026-08-30T15:20:00Z",
    status: "COMPLETED",
    progressPercent: 100,
    frameworks: ["LGPD", "GDPR", "ISO 27001"],
    findingsCount: {
      total: 6,
      critical: 2,
      high: 2,
      medium: 1,
      low: 1,
    },
  },
  {
    id: "INV-2024-0046",
    title: "Termos de Uso e Política de Privacidade do App Mobile",
    documentName: "termos_uso_mobile_v1.md",
    documentHash: "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08",
    fileSizeBytes: 112400,
    createdAt: "2026-08-29T10:15:00Z",
    updatedAt: "2026-08-29T11:45:00Z",
    status: "COMPLETED",
    progressPercent: 100,
    frameworks: ["LGPD", "OWASP"],
    findingsCount: {
      total: 4,
      critical: 1,
      high: 1,
      medium: 1,
      low: 1,
    },
  },
];

export const MOCK_FINDINGS: Finding[] = [
  {
    id: "FIND-01",
    investigationId: "INV-2024-0047",
    title: "Retenção Indeterminada de Dados Pessoais de Usuários",
    description: "A Seção 2.1 estipula armazenamento por prazo indeterminado sem justificativa legal de término de tratamento, violando o princípio da necessidade.",
    severity: "CRITICAL",
    framework: "LGPD",
    articleOrControl: "Art. 15 e Art. 16 (Término do Tratamento e Eliminação)",
    agentId: "lgpd-specialist",
    agentName: "Especialista LGPD (Gemini Flash)",
    confidence: 0.95,
    evidenceQuote: "Dados cadastrais e histórico de transações de usuários serão armazenados por prazo indeterminado para fins de inteligência de negócios...",
    evidenceHash: "8f4b2a1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b7c6d5e4f3a",
    remediationSuggestion: "Definir prazo máximo de retenção de 5 anos após o encerramento da conta e criar rotina de expurgo automatizado.",
    status: "OPEN",
    challengedByCritic: true,
    criticVerdict: "Validado: Não há base legal legítima para prazo perpétuo na LGPD sem anonimização efetiva.",
  },
  {
    id: "FIND-02",
    investigationId: "INV-2024-0047",
    title: "Prazo Excessivo para Atendimento ao Direito de Eliminação (90 dias)",
    description: "A Seção 3.1 estabelece 90 dias úteis para análise de exclusão, excedendo o prazo razoável previsto pelo GDPR (30 dias / 1 mês).",
    severity: "CRITICAL",
    framework: "GDPR",
    articleOrControl: "Art. 17 (Right to Erasure) & Art. 12(3)",
    agentId: "gdpr-specialist",
    agentName: "Especialista GDPR (Gemini Flash)",
    confidence: 0.92,
    evidenceQuote: "Solicitações de exclusão de dados pessoais feitas por titulares serão avaliadas pela equipe jurídica em até 90 dias úteis.",
    evidenceHash: "7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b7c6d5e4f3a2b1c0d9e8f7a6b",
    remediationSuggestion: "Reduzir o prazo de resposta para 30 dias corridos conforme exigência do Artigo 12(3) do GDPR.",
    status: "OPEN",
    challengedByCritic: true,
    criticVerdict: "Confirmado: O GDPR estipula prazo de 1 mês, prorrogável apenas mediante justificativa de complexidade notificada ao titular.",
  },
  {
    id: "FIND-03",
    investigationId: "INV-2024-0047",
    title: "Logs com Endereços IP Retidos sem Anonimização",
    description: "A Seção 2.2 retém logs por 30 dias contendo identificadores pessoais sem processo de pseudonimização ou hash de IP.",
    severity: "HIGH",
    framework: "ISO 27001",
    articleOrControl: "Controle A.8.10 (Information Deletion) & A.8.15 (Logging)",
    agentId: "iso-specialist",
    agentName: "Especialista ISO 27001 (Gemini Flash)",
    confidence: 0.88,
    evidenceQuote: "Logs de acesso a servidores e requisições HTTP serão retidos por 30 (trinta) dias, sem expurgo programado de registros que contenham endereços IP...",
    evidenceHash: "1e0f9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f",
    remediationSuggestion: "Aplicar mascaramento (masking) no último octeto do IP no momento da ingestão do log.",
    status: "OPEN",
    challengedByCritic: false,
  },
  {
    id: "FIND-04",
    investigationId: "INV-2024-0047",
    title: "Senhas Compartilhadas em Bases Analíticas",
    description: "A Seção 4.1 menciona o uso de credenciais genéricas compartilhadas pela engenharia, violando o princípio do menor privilégio e rastreabilidade.",
    severity: "HIGH",
    framework: "ISO 27001",
    articleOrControl: "Controle A.5.15 (Access Control) & A.9.2 (User Access Management)",
    agentId: "iso-specialist",
    agentName: "Especialista ISO 27001 (Gemini Flash)",
    confidence: 0.96,
    evidenceQuote: "Bases de dados analíticas utilizam senhas compartilhadas restritas ao time de engenharia.",
    evidenceHash: "5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d",
    remediationSuggestion: "Migrar para autenticação federada (SSO/IAM) com contas nominais e auditoria de sessão.",
    status: "OPEN",
    challengedByCritic: true,
    criticVerdict: "Crítico: Credenciais compartilhadas anulam a rastreabilidade exigida pela ISO 27001.",
  },
];

export const MOCK_TRUST_GRAPH_INITIAL: TrustGraphData = {
  investigation_id: "INV-2024-0047",
  total_nodes: 10,
  valid_nodes: 10,
  invalid_nodes: 0,
  nodes: [
    {
      id: "req-lgpd-16",
      type: "requirement",
      source: "LGPD Art. 16 (Eliminação)",
      valid: true,
      confidence: 1.0,
      jurisdiction: "BR",
      content_hash: "sha256-lgpd-art16-v1",
      details: "Exige eliminação após término da finalidade do tratamento de dados pessoais.",
    },
    {
      id: "req-gdpr-5",
      type: "requirement",
      source: "GDPR Art. 5(1)(e) (Storage Limitation v1)",
      valid: true,
      confidence: 1.0,
      jurisdiction: "EU",
      content_hash: "sha256-gdpr-art5-v1",
      details: "Dados pessoais não devem ser mantidos por mais tempo do que o necessário.",
    },
    {
      id: "req-iso-a810",
      type: "requirement",
      source: "ISO 27001 A.8.10 (Data Deletion)",
      valid: true,
      confidence: 1.0,
      jurisdiction: "GLOBAL",
      content_hash: "sha256-iso-a810-v1",
      details: "Diretrizes para expurgo seguro e retenção de registros de auditoria.",
    },
    {
      id: "ag-pii",
      type: "agent",
      source: "PII Scanner (Gemma 2B)",
      valid: true,
      confidence: 0.98,
      jurisdiction: "ALL",
      content_hash: "sha256-agent-pii-v1",
      details: "Varredura preliminar de CPF, e-mails e identificadores confidenciais.",
    },
    {
      id: "ag-lgpd",
      type: "agent",
      source: "Especialista LGPD (Gemini 2.5 Flash)",
      valid: true,
      confidence: 0.94,
      jurisdiction: "BR",
      content_hash: "sha256-agent-lgpd-v1",
      details: "Especialista de conformidade nacional brasileira.",
    },
    {
      id: "ag-gdpr",
      type: "agent",
      source: "Especialista GDPR (Gemini 2.5 Flash)",
      valid: true,
      confidence: 0.91,
      jurisdiction: "EU",
      content_hash: "sha256-agent-gdpr-v1",
      details: "Especialista em privacidade europeia.",
    },
    {
      id: "ev-retencao-infinita",
      type: "evidence",
      source: "politica_retencao_dados.pdf §2.1",
      valid: true,
      confidence: 0.95,
      jurisdiction: "BR/EU",
      content_hash: "8f4b2a1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b7c6d5e4f3a",
      details: "Citação exata: '...armazenados por prazo indeterminado para fins de inteligência...'",
    },
    {
      id: "ev-prazo-90dias",
      type: "evidence",
      source: "politica_retencao_dados.pdf §3.1",
      valid: true,
      confidence: 0.92,
      jurisdiction: "EU",
      content_hash: "7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b7c6d5e4f3a2b1c0d9e8f7a6b",
      details: "Citação exata: '...avaliadas pela equipe jurídica em até 90 dias úteis.'",
    },
    {
      id: "find-01-node",
      type: "finding",
      source: "FIND-01: Retenção Indeterminada",
      valid: true,
      confidence: 0.95,
      jurisdiction: "BR",
      content_hash: "sha256-find-01",
      details: "Não conformidade com o Art. 16 da LGPD. Remediação requerida.",
    },
    {
      id: "find-02-node",
      type: "finding",
      source: "FIND-02: Prazo Excessivo 90d",
      valid: true,
      confidence: 0.92,
      jurisdiction: "EU",
      content_hash: "sha256-find-02",
      details: "Violação do limite de 30 dias do Art. 12 do GDPR.",
    },
  ],
  edges: [
    { from: "req-lgpd-16", to: "find-01-node" },
    { from: "ag-lgpd", to: "find-01-node" },
    { from: "ev-retencao-infinita", to: "find-01-node" },
    { from: "ag-pii", to: "ev-retencao-infinita" },
    { from: "req-gdpr-5", to: "find-02-node" },
    { from: "ag-gdpr", to: "find-02-node" },
    { from: "ev-prazo-90dias", to: "find-02-node" },
    { from: "req-iso-a810", to: "ev-retencao-infinita" },
  ],
};

export const SAMPLE_POLICIES = [
  {
    name: "Política de Retenção de Dados — Sintética BR/EU",
    description: "Cenário oficial da demo multi-jurisdição (LGPD + GDPR + ISO 27001)",
    frameworks: ["LGPD", "GDPR", "ISO 27001"],
    sampleContent: `POLÍTICA CORPORATIVA DE RETENÇÃO E PRIVACIDADE DE DADOS
Versão 2.4 — Setembro 2026

1. OBJETIVO E ESCOPO
Esta política define as diretrizes para armazenamento, tratamento e descarte de dados pessoais e corporativos tratados nos ambientes de produção do AEGIS Group no Brasil e União Europeia.

2. PRAZOS DE RETENÇÃO
2.1. Dados cadastrais e histórico de transações de usuários serão armazenados por prazo indeterminado para fins de inteligência de negócios e personalização de serviços.
2.2. Logs de acesso a servidores e requisições HTTP serão retidos por 30 (trinta) dias, sem expurgo programado de registros que contenham endereços IP ou identificadores pessoais.
2.3. Documentos fiscais e comprovantes bancários serão mantidos pelo prazo de 5 (cinco) anos conforme legislação tributária aplicável.

3. DIREITO AO ESQUECIMENTO E ELIMINAÇÃO
3.1. Solicitações de exclusão de dados pessoais feitas por titulares serão avaliadas pela equipe jurídica em até 90 dias úteis.
3.2. Dados mantidos em backups frios não são afetados por solicitações de exclusão e serão sobrescritos apenas no ciclo padrão de 2 anos.

4. SEGURANÇA E CRIPTOGRAFIA
4.1. Dados em trânsito são protegidos com TLS 1.3. Bases de dados analíticas utilizam senhas compartilhadas restritas ao time de engenharia.`,
  },
];
